### PR TITLE
fixed login errors

### PR DESCRIPTION
**Pull request by furbyhaxx**
amazon added a 302 redirect, and the appproval alert detection was also stuck in a loop.
At least for the DE market

### CODE REVIEW

**Comment by mkb79** [comment]
Will look at this later. In my opinion you should only use follow_redirects=True when instantiate the httpx client. Then you don't need to do this on every request!

Good work!

**Comment by glitchwizard** [comment]
oh, I think my MR #74 is addressing this same thing.

**Comment by glitchwizard** [comment]
I went and made the changes in this branch into my app, and it worked. Thanks for this @afkfurby

**Comment by mkb79** [comment]
@afkfurby I've reworked your PR. Can you try this out please. I could login to my account with these changes.

**Comment by furbyhaxx** [comment]
@mkb79 sorry doesn't work for me. But I have no idea why. It always states that my guess of the captcha was wrong.

**Comment by mkb79** [comment]
That is really strange. I will look on the code again.

**Review by furbyhaxx — COMMENTED** [review]
works, just don't login with "with_username=True", get's me trapped in a captcha loop

**Pull request closed without merging**
