### PR TITLE
Login with username

### PR DESCRIPTION
**Pull request by mkb79**
Can someone with Audible account which use a username instead of Amazon account Test out this?

### CODE REVIEW

**Comment by blurfl** [comment]
I am able to get a list of the books for my Audible username/pass using "Hello Library"

**Comment by blurfl** [comment]
Using a fresh VM (so unregistered, right?), I'm not able to get past the CAPTCHA step with register=True.

**Comment by mkb79** [comment]
> Using a fresh VM (so unregistered, right?)

Yeah, if you use a fresh login, then you are unregistered. 

> I'm not able to get past the CAPTCHA step with register=True

That's really strange. Set `register=True` doesn't have any impact on login progress. If you can't go around the CAPTCHA, please try the following:

```python
from audible import Authenticator

auth = Authenticator.from_login_external(YOUR_LOCAL_CODE)
auth.to_file(FILENAME)
auth.register_device()
auth.to_file()
```

**Comment by blurfl** [comment]
Trying that, the URL takes me to the Amazon login instead of the Audible login. I bailed out to come ask whether that is expected?

**Comment by mkb79** [comment]
> Trying that, the URL takes me to the Amazon login instead of the Audible login. I bailed out to come ask whether that is expected?

Sorry, forgot one thing. Please add `with_username=True` to `Authenticator.from_login_external`

So your code schould look:

```python
from audible import Authenticator

auth = Authenticator.from_login_external(YOUR_LOCAL_CODE, with_username=True)
auth.to_file(FILENAME)
auth.register_device()
auth.to_file()
```

**Comment by mkb79** [comment]
I fixed a bug with last commit. Now `Authenticator.from_login_external` should work as expected.

**Comment by blurfl** [comment]
After your update, on the unregistered VM I was able to create the local auth file and after that to log in using the Audible username/password as expected and get the book list for the account. 👍

**Pull request merged**
